name: File Check CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for required files
        run: |
          required_files=("README.md" "server/main.cpp" "server/CMakeLists.txt" "docker-compose.yml")
          missing_files=()
          
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              missing_files+=("$file")
            fi
          done

          if [ ${#missing_files[@]} -ne 0 ]; then
            echo "Error: The following required files are missing:"
            for file in "${missing_files[@]}"; do
              echo "$file"
            done
            exit 1
          else
            echo "All required files are present."
          fi
